[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[build]
  publish = "public"
  command = "npm run build"
  functions = "lambda"
[build.environment]
  NODE_VERSION = "14"
[[plugins]]
  package = "netlify-plugin-gatsby-cache"